import { StyleSheet, Dimensions, Platform } from 'react-native';

// Static fallback for StyleSheet (cannot use hooks)
const { width: staticW, height: staticH } = Dimensions.get('window');
export const isLandscapeMobile = staticW > staticH && staticH < 500;

export const THEMES = {
  classic: { primary: '#1e392a', secondary: '#2ecc71', background: '#0F1F15', border: 'rgba(46,204,113,0.15)' },
  luxury: { primary: '#4a1010', secondary: '#e67e22', background: '#1a0505', border: 'rgba(230,126,34,0.15)' },
  ocean: { primary: '#102a4a', secondary: '#3498db', background: '#050c1a', border: 'rgba(52,152,219,0.15)' },
  midnight: { primary: '#1a1a1a', secondary: '#95a5a6', background: '#0a0a0a', border: 'rgba(149,165,166,0.15)' },
};

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#0F1F15' },
  mainRow: { flex: 1, flexDirection: 'row' },
  mainContent: { flex: 1, flexDirection: 'column' },
  logSidebar: {
    position: 'absolute',
    right: 0,
    top: 0,
    bottom: 0,
    width: isLandscapeMobile ? 240 : 300,
    backgroundColor: 'rgba(15, 31, 21, 0.98)',
    borderLeftWidth: 1,
    borderLeftColor: 'rgba(232,217,176,0.2)',
    display: 'flex',
    flexDirection: 'column',
    paddingTop: Platform.OS === 'ios' ? 50 : 30,
    zIndex: 2000,
  },
  settingsSection: { padding: 16, gap: 12 },
  settingsRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  settingsLabel: { color: 'rgba(232,217,176,0.6)', fontSize: 13, fontWeight: '600' },
  langBtnLarge: { backgroundColor: 'rgba(232,217,176,0.1)', paddingHorizontal: 12, paddingVertical: 8, borderRadius: 8, minWidth: 100, alignItems: 'center' },
  langBtnTextLarge: { color: '#E8D9B0', fontSize: 13, fontWeight: 'bold' },
  themeSwitcherLarge: { flexDirection: 'row', gap: 10 },
  themeOptionLarge: { width: 24, height: 24, borderRadius: 12, borderWidth: 1.5, borderColor: 'rgba(255,255,255,0.2)' },
  logDivider: { height: 1, backgroundColor: 'rgba(232,217,176,0.1)', marginHorizontal: 16, marginVertical: 8 },
  logSidebarHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 16, borderBottomWidth: 1, borderBottomColor: 'rgba(255,255,255,0.1)' },
  logSidebarTitle: { color: '#E8D9B0', fontSize: 16, fontWeight: 'bold' },
  logCloseBtn: { padding: 4 },
  logCloseText: { color: '#e74c3c', fontSize: 14, fontWeight: 'bold' },
  logScroll: { flex: 1, padding: 12 },
  logItem: { marginBottom: 12, backgroundColor: 'rgba(255,255,255,0.05)', padding: 8, borderRadius: 8 },
  logTime: { color: 'rgba(255,255,255,0.4)', fontSize: 10, marginBottom: 4 },
  logMessage: { color: '#fff', fontSize: 13, lineHeight: 18 },
  logEmpty: { color: 'rgba(255,255,255,0.3)', fontSize: 13, textAlign: 'center', marginTop: 20, fontStyle: 'italic' },
  loadingScreen: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: '#0F1F15' },
  loadingEmoji: { fontSize: 72, marginBottom: 12 },
  loadingTitle: { fontSize: 40, fontWeight: '900', color: '#E8D9B0', letterSpacing: 6 },
  loadingSubtitle: { fontSize: 14, color: 'rgba(232,217,176,0.45)', marginTop: 8, letterSpacing: 2, fontWeight: '500' },
  rulesHeading: { fontSize: 18, fontWeight: 'bold', color: '#f1c40f', marginTop: 16, marginBottom: 8 },
  rulesText: { fontSize: 14, color: '#fff', lineHeight: 22, marginBottom: 8 },
  menuContainer: { marginTop: 60, width: '100%', maxWidth: 300, gap: 14 },
  menuButton: { backgroundColor: 'transparent', paddingVertical: 14, borderRadius: 30, alignItems: 'center', elevation: 4 },
  exitButton: { backgroundColor: 'rgba(231,76,60,0.08)' },
  menuButtonText: { color: 'white', fontSize: 16, fontWeight: '800', letterSpacing: 1 },
  header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: isLandscapeMobile ? 10 : 16, paddingVertical: isLandscapeMobile ? 0 : 8, borderBottomWidth: 1, borderBottomColor: 'rgba(232,217,176,0.1)' },
  headerTitle: { fontSize: isLandscapeMobile ? 12 : 18, fontWeight: '700', color: '#E8D9B0', letterSpacing: isLandscapeMobile ? 1 : 2 },
  headerRight: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  seqCount: { fontSize: 12, color: 'rgba(232,217,176,0.6)', backgroundColor: 'rgba(232,217,176,0.08)', paddingHorizontal: 8, paddingVertical: 3, borderRadius: 8 },
  openLogBtn: { backgroundColor: 'rgba(255,255,255,0.1)', paddingHorizontal: 12, paddingVertical: 6, borderRadius: 16 },
  openLogText: { color: '#E8D9B0', fontSize: 12, fontWeight: 'bold' },
  opponentsRow: { flexDirection: 'row', paddingHorizontal: isLandscapeMobile ? 3 : 8, paddingVertical: isLandscapeMobile ? 0 : 10, gap: isLandscapeMobile ? 2 : 6 },
  aiBadge: { flex: 1, backgroundColor: 'rgba(255,255,255,0.04)', borderRadius: isLandscapeMobile ? 4 : 10, padding: isLandscapeMobile ? 2 : 8, borderWidth: 1, borderColor: 'rgba(255,255,255,0.06)', position: 'relative' },
  aiBadgeActive: { backgroundColor: 'rgba(241,196,15,0.08)', borderColor: 'rgba(241,196,15,0.3)' },
  aiBadgeFinished: { opacity: 0.5 },
  aiBadgeHeader: { flexDirection: 'row', alignItems: 'center', gap: isLandscapeMobile ? 2 : 4, marginBottom: isLandscapeMobile ? 1 : 4 },
  aiEmoji: { fontSize: isLandscapeMobile ? 10 : 12 },
  aiName: { fontSize: isLandscapeMobile ? 9 : 11, fontWeight: '600', color: 'rgba(255,255,255,0.6)', flexShrink: 1 },
  aiNameActive: { color: '#f1c40f' },
  aiCardCount: { flexDirection: 'row', alignItems: 'baseline', gap: isLandscapeMobile ? 2 : 3 },
  aiCardCountText: { fontSize: isLandscapeMobile ? 10 : 18, fontWeight: '700', color: 'rgba(255,255,255,0.8)' },
  aiCardLabel: { fontSize: isLandscapeMobile ? 7 : 9, color: 'rgba(255,255,255,0.3)' },
  aiFinishedText: { fontSize: isLandscapeMobile ? 10 : 14, fontWeight: '700', color: '#2ecc71' },
  thinkingDots: { marginTop: isLandscapeMobile ? 1 : 2 },
  thinkingText: { fontSize: isLandscapeMobile ? 7 : 9, color: 'rgba(241,196,15,0.6)', fontStyle: 'italic' },
  aiScoreBadge: { position: 'absolute', bottom: isLandscapeMobile ? -2 : -6, right: isLandscapeMobile ? -2 : -6, backgroundColor: '#0F1F15', paddingHorizontal: isLandscapeMobile ? 4 : 6, paddingVertical: isLandscapeMobile ? 1 : 2, borderRadius: 8, borderWidth: 1, borderColor: 'rgba(232,217,176,0.2)' },
  aiScoreText: { color: '#E8D9B0', fontSize: isLandscapeMobile ? 7 : 9, fontWeight: 'bold' },
  statusText: { flex: 1, fontSize: isLandscapeMobile ? 9 : 11, color: 'rgba(232,217,176,0.5)', textAlign: 'center', marginHorizontal: isLandscapeMobile ? 4 : 8 },
  tableArea: { flex: 1, marginHorizontal: isLandscapeMobile ? 2 : 4, borderRadius: isLandscapeMobile ? 10 : 16, borderWidth: 1, overflow: 'hidden' },
  tableContainer: { flex: 1, padding: 4 },
  sequencesWrapContainer: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, justifyContent: 'center', alignItems: 'flex-start', paddingLeft: 50 },
  sequenceRow: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  sequenceRowExpanded: { backgroundColor: 'rgba(255,255,255,0.08)', borderRadius: 12 },
  sequenceRowTargetable: { 
    borderColor: '#3498db', 
    borderWidth: 2, 
    borderStyle: 'dashed',
    backgroundColor: 'rgba(52,152,219,0.1)'
  },
  sequenceBadge: { backgroundColor: 'rgba(46,204,113,0.15)', paddingHorizontal: 6, paddingVertical: 3, borderRadius: 6, minWidth: 44, alignItems: 'center' },
  sequenceBadgeText: { fontSize: 9, color: '#2ecc71', fontWeight: '600' },
  sequenceCards: { flexDirection: 'row', paddingVertical: 2, paddingRight: 4 },
  emptyTable: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  emptyTableEmoji: { fontSize: 48, marginBottom: 12, opacity: 0.3 },
  emptyTableText: { color: 'rgba(255,255,255,0.25)', fontSize: 14, fontWeight: '500' },
  emptyTableHint: { color: 'rgba(255,255,255,0.12)', fontSize: 11, marginTop: 4 },
  deckCenterWrapper: { alignItems: 'center', justifyContent: 'center', position: 'relative' },
  flyingCardContainer: { position: 'absolute', zIndex: 50 },
  deckBase2: { transform: [{ translateY: 4 }, { translateX: -2 }], zIndex: 1 },
  deckBase1: { transform: [{ translateY: 2 }, { translateX: -1 }], zIndex: 2 },
  deckTop: { zIndex: 3 },
  remainingDeckContainer: { position: 'absolute', top: 10, left: 10, width: 36, height: 50, zIndex: 100, elevation: 5 },
  remainingDeckBadge: { position: 'absolute', bottom: 2, right: 2, backgroundColor: '#3498db', borderRadius: 10, width: 18, height: 18, justifyContent: 'center', alignItems: 'center', zIndex: 20, borderWidth: 1, borderColor: '#fff' },
  remainingDeckText: { color: '#fff', fontSize: 8, fontWeight: '900' },
  humanArea: { paddingBottom: isLandscapeMobile ? 0 : 20, borderTopWidth: 1, borderTopColor: 'rgba(232,217,176,0.1)', overflow: 'visible' as any },
  humanHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: isLandscapeMobile ? 6 : 16, paddingVertical: isLandscapeMobile ? 0 : 8 },
  humanInfo: { flexDirection: 'row', alignItems: 'center', gap: isLandscapeMobile ? 4 : 8 },
  humanName: { color: 'rgba(255,255,255,0.7)', fontWeight: '600', fontSize: isLandscapeMobile ? 11 : 14 },
  humanNameActive: { color: '#E8D9B0' },
  humanScoreBadge: { backgroundColor: 'rgba(232,217,176,0.1)', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 12 },
  humanScoreText: { color: '#E8D9B0', fontSize: 12, fontWeight: 'bold' },
  yourTurnBadge: { fontSize: 9, fontWeight: '800', color: '#0F1F15', backgroundColor: '#f1c40f', paddingHorizontal: 6, paddingVertical: 2, borderRadius: 4 },
  actionButtons: { flexDirection: 'row', gap: isLandscapeMobile ? 4 : 8 },
  actionBtn: { paddingHorizontal: isLandscapeMobile ? 8 : 16, paddingVertical: isLandscapeMobile ? 3 : 8, borderRadius: 20, minWidth: isLandscapeMobile ? 40 : 60, alignItems: 'center' },
  actionBtnDisabled: { opacity: 0.3 },
  passBtnStyle: { backgroundColor: 'rgba(231,76,60,0.2)', borderWidth: 1, borderColor: 'rgba(231,76,60,0.4)' },
  playBtnStyle: { backgroundColor: 'rgba(46,204,113,0.2)', borderWidth: 1, borderColor: 'rgba(46,204,113,0.4)' },
  actionBtnText: { color: 'white', fontWeight: '700', fontSize: isLandscapeMobile ? 11 : 13 },
  gameOverOverlay: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(0,0,0,0.85)', justifyContent: 'center', alignItems: 'center', padding: 24, zIndex: 9999 },
  gameOverCard: { backgroundColor: '#1A2E23', borderRadius: 24, padding: 28, width: '100%', maxWidth: 380, maxHeight: '90%', alignItems: 'center', borderWidth: 1, borderColor: 'rgba(232,217,176,0.15)' },
  gameOverEmoji: { fontSize: 56, marginBottom: 8 },
  gameOverTitle: { fontSize: 28, fontWeight: '800', color: '#E8D9B0', marginBottom: 4 },
  gameOverSubtitle: { fontSize: 13, color: 'rgba(232,217,176,0.5)', marginBottom: 20, fontWeight: '500' },
  winningMeldContainer: { backgroundColor: 'rgba(0,0,0,0.3)', padding: 12, borderRadius: 16, alignItems: 'center', marginBottom: 16, width: '100%' },
  winningMeldTitle: { color: '#f1c40f', fontSize: 11, fontWeight: 'bold', marginBottom: 8, textTransform: 'uppercase' },
  winningMeldRow: { flexDirection: 'row' },
  standingsContainer: { width: '100%', gap: 6, marginBottom: 24 },
  standingRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 10, paddingHorizontal: 14, backgroundColor: 'rgba(255,255,255,0.04)', borderRadius: 12 },
  standingRowFirst: { backgroundColor: 'rgba(241,196,15,0.1)', borderWidth: 1, borderColor: 'rgba(241,196,15,0.2)' },
  standingRowHuman: { borderLeftWidth: 3, borderLeftColor: '#3498db' },
  standingMedal: { fontSize: 20, marginRight: 12, width: 30, textAlign: 'center' },
  standingLeft: { flex: 1 },
  standingRight: { alignItems: 'flex-end' },
  standingName: { fontSize: 15, fontWeight: '600', color: 'rgba(255,255,255,0.8)' },
  standingNameFirst: { color: '#f1c40f' },
  standingOrder: { fontSize: 12, color: 'rgba(255,255,255,0.3)', fontWeight: '500' },
  standingPoints: { fontSize: 14, fontWeight: 'bold', color: '#fff' },
  standingTotalScore: { fontSize: 11, color: 'rgba(255,255,255,0.4)', fontWeight: 'normal' },
  gameOverActions: { width: '100%', marginTop: 10, gap: 12, alignItems: 'center' },
  restartButton: { backgroundColor: '#2ecc71', paddingHorizontal: 32, paddingVertical: 14, borderRadius: 30, width: '100%', alignItems: 'center' },
  restartButtonText: { color: 'white', fontWeight: '800', fontSize: 16, letterSpacing: 1 },
  hintPanel: { backgroundColor: 'rgba(0,0,0,0.3)', borderRadius: 8, padding: 12, marginTop: -8, marginBottom: 14, borderWidth: 1, borderColor: 'rgba(255,255,255,0.1)' },
  hintTitle: { color: 'rgba(255,255,255,0.8)', fontSize: 12, fontWeight: '600', marginBottom: 8 },
  hintRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  hintChip: { flexDirection: 'row', alignItems: 'center', backgroundColor: 'rgba(255,255,255,0.1)', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 12, borderWidth: 1, borderColor: 'rgba(255,255,255,0.2)' },
  hintCard: { color: '#E8D9B0', fontWeight: '700', fontSize: 13 },
  hintArrow: { color: '#3498db', fontWeight: '800', fontSize: 12 },
  hintLabel: { color: 'rgba(255,255,255,0.4)', fontSize: 10, marginLeft: 4 },
  hintNote: { color: 'rgba(231,76,60,0.8)', fontSize: 11, fontStyle: 'italic', marginTop: 8 },
  leftoverCardsSection: { marginTop: 16, width: '100%', alignItems: 'center', backgroundColor: 'rgba(0,0,0,0.2)', padding: 12, borderRadius: 12 },
  leftoverCardsTitle: { fontSize: 12, fontWeight: 'bold', color: 'rgba(255,255,255,0.3)', marginBottom: 8, textTransform: 'uppercase', letterSpacing: 1 },
  leftoverCardsRow: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'center', gap: -12 },
  leftoverCardWrapper: { transform: [{ scale: 0.8 }] },
  hintBtnStyle: { backgroundColor: 'rgba(241,196,15,0.15)', borderWidth: 1, borderColor: 'rgba(241,196,15,0.4)' },
  hintNotification: {
    position: 'absolute',
    top: 60,
    left: 20,
    right: 20,
    backgroundColor: '#0F1F15',
    padding: 16,
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: '#f1c40f',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    zIndex: 1000,
    elevation: 10,
    ...Platform.select({
      web: { boxShadow: '0px 4px 8px rgba(241, 196, 15, 0.3)' } as any,
      default: {
        shadowColor: '#f1c40f',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
      }
    }),
  },
  hintNotificationText: { color: '#E8D9B0', fontSize: 14, fontWeight: '700', flex: 1 },
  hintCloseBtn: { padding: 8, marginLeft: 12 },
  hintCloseText: { color: 'rgba(255,255,255,0.4)', fontSize: 18, fontWeight: 'bold' },
  musicBtn: { backgroundColor: 'rgba(231,76,60,0.1)', paddingHorizontal: 12, paddingVertical: 6, borderRadius: 8, borderWidth: 1, borderColor: 'rgba(231,76,60,0.3)' },
  musicBtnActive: { backgroundColor: 'rgba(46,204,113,0.1)', borderColor: 'rgba(46,204,113,0.3)' },
  musicBtnText: { color: '#E8D9B0', fontSize: 11, fontWeight: 'bold' },
  tutorialOverlay: { ...StyleSheet.absoluteFillObject, zIndex: 9999 },
  tutorialBackdrop: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(0,0,0,0.7)' },
  tutorialHighlight: {
    position: 'absolute',
    borderWidth: 2,
    borderColor: '#f1c40f',
    backgroundColor: 'rgba(241,196,15,0.1)',
    borderRadius: 8,
  },
  tutorialBox: {
    position: 'absolute',
    left: 20,
    right: 20,
    backgroundColor: '#fff',
    borderRadius: 28,
    padding: 28,
    ...Platform.select({
      web: { boxShadow: '0px 25px 40px rgba(0, 0, 0, 0.25)' } as any,
      default: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 25 },
        shadowOpacity: 0.25,
        shadowRadius: 40,
      }
    }),
    elevation: 30,
    borderWidth: 1.5,
    borderColor: 'rgba(52,152,219,0.15)',
  },
  tutorialHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16 },
  tutorialStepCount: { color: '#3498db', fontWeight: '900', fontSize: 13, textTransform: 'uppercase', letterSpacing: 1.5 },
  tutorialCloseMini: { padding: 6 },
  tutorialTitle: { fontSize: 26, fontWeight: '900', color: '#2c3e50', marginBottom: 12, letterSpacing: -0.5 },
  tutorialDesc: { fontSize: 16, color: '#576574', lineHeight: 26, marginBottom: 28 },
  tutorialFooter: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  tutorialSkipBtn: { paddingVertical: 12, paddingHorizontal: 16 },
  tutorialSkipText: { color: '#95a5a6', fontWeight: 'bold', fontSize: 14 },
  tutorialNextBtn: { 
    backgroundColor: '#3498db', 
    paddingHorizontal: 32, 
    paddingVertical: 14, 
    borderRadius: 16,
    ...Platform.select({
      web: { boxShadow: '0px 4px 8px rgba(52, 152, 219, 0.3)' } as any,
      default: {
        shadowColor: '#3498db',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
      }
    }),
    elevation: 5,
  },
  tutorialNextText: { color: '#fff', fontWeight: '900', fontSize: 16 },
  highlightPulse: {
    ...StyleSheet.absoluteFillObject,
    borderWidth: 3,
    borderColor: '#f1c40f',
    borderRadius: 12,
    opacity: 0.5,
  },
  ceremonyOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.9)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10000,
  },
  ceremonyCard: {
    backgroundColor: '#1A2E23',
    padding: 40,
    borderRadius: 30,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#f1c40f',
    ...Platform.select({
      web: { boxShadow: '0px 0px 20px rgba(241, 196, 15, 0.5)' } as any,
      default: {
        shadowColor: '#f1c40f',
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.5,
        shadowRadius: 20,
      }
    }),
    elevation: 20,
  },
  ceremonyEmoji: { fontSize: 80, marginBottom: 10 },
  ceremonySongText: { 
    color: '#f1c40f', 
    fontSize: 64, 
    fontWeight: '900', 
    letterSpacing: 8,
    ...Platform.select({
      web: { textShadow: '0px 0px 20px rgba(241, 196, 15, 0.5)' } as any,
      default: {
        textShadowColor: 'rgba(241,196,15,0.5)',
        textShadowOffset: { width: 0, height: 0 },
        textShadowRadius: 20,
      }
    })
  },
  ceremonyTitle: { color: 'rgba(255,255,255,0.8)', fontSize: 18, fontWeight: '900', letterSpacing: 4, marginTop: 10 },
  ceremonyName: { color: '#fff', fontSize: 36, fontWeight: '800', marginVertical: 10 },
  ceremonySubtitle: { color: 'rgba(255,255,255,0.6)', fontSize: 14, fontWeight: '500' },
  particleContainer: { position: 'absolute', width: '100%', height: '100%', pointerEvents: 'none' },
  ceremonyParticle: { position: 'absolute' },
  deadLabel: {
    backgroundColor: '#e74c3c',
    paddingHorizontal: 4,
    paddingVertical: 1,
    borderRadius: 4,
    marginTop: 2,
  },
  deadLabelText: {
    color: '#fff',
    fontSize: 8,
    fontWeight: '900',
  }
});
